spring.application.name=Employee Management System

spring.main.banner-mode=off


# Database Configuration for MySQL/MariaDB
spring.datasource.url=jdbc:postgresql://localhost:5432/ems_db
spring.datasource.username=akentech
spring.datasource.password=Bundes9898
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG



# JWT Configuration
app.jwt.secret=Om0c43Mt5k0HG14jtLn9GCYhN/5NYPXv+Y1IUuryJB/YOvaT8UvbH5/7tEaNJIDI+waXzUMb640cZbDGboj9+A==
app.jwt.access-token-expiration-ms=2592000000
app.jwt.refresh-token-expiration-ms=5184000000


# Profile picture settings
profile.picture.upload-dir=profile-pictures
profile.picture.max-size=5MB
profile.picture.allowed-types=image/jpeg,image/png,image/gif
profile.picture.thumbnail.width=150
profile.picture.thumbnail.height=150


server.port=8080
