spring.application.name=Employee Management System
spring.main.banner-mode=off

# Database Configuration for MySQL/MariaDB
spring.datasource.url=jdbc:mysql://localhost:3306/ems_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Bundes9898!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging (keep only what we need)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.springframework.jdbc=DEBUG


# JWT Configuration
app.jwt.secret=utW4YTPSy1WY/T2R6mdCRBlvEcOOhHyxfUBxDuwRwzu4EGknNggUDU/7yJljxO3B7rttngzXEsVqEo2sB/zw5A==
app.jwt.access-token-expiration-ms=2592000000
app.jwt.refresh-token-expiration-ms=5184000000

# Admin user configuration
admin.username=admin
admin.password=admin123
admin.name=Administrator

# File upload
file.upload-dir=uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.resolve-lazily=true

server.port=8080